// これが index.html と繋がるための「器」の名前だよ
const MASTER_DATABASE = {
  models: [
    // --- ここに日本人美女 50パターンを結合 ---
    { name: "JP-01 王道清純ボブ", prompt: "Stunning Japanese woman, soft bob hair, pure aura, highly detailed skin texture, almond eyes, soft daylight" },
    { name: "JP-02 愛されシースルー", prompt: "Cute Japanese woman, see-through bangs, round face, moist puppy eyes, soft skin, casual look" },
    { name: "JP-03 茶髪ポニーテール", prompt: "Healthy Japanese woman, brown ponytail, clear double eyelids, vibrant tanned skin, bright smile" },
    { name: "JP-04 クール・ショート", prompt: "Cool Japanese woman, very short black hair, sharp jawline, sophisticated urban model style" },
    { name: "JP-05 癒やし系ミディアム", prompt: "Gentle Japanese woman, fluffy medium hair, drooping eyes, fair skin, motherly aura" },
    { name: "JP-06 港区キャリア系", prompt: "Intellectual Japanese woman, center-parted long hair, sharp nose, dignified facial features" },
    { name: "JP-07 お嬢様ハーフアップ", prompt: "Elegant Japanese woman, half-up hair, tear bags under eyes, refined and classy look" },
    { name: "JP-08 アンニュイ・シニヨン", prompt: "Sensual Japanese woman, wet hair styled in a chignon, downcast eyes, mysterious and sexy" },
    { name: "JP-09 そばかすヘルシー", prompt: "Innocent Japanese woman, messy bun hair, slight freckles, natural youthful charm, sun-kissed" },
    { name: "JP-10 ミステリアス・ウルフ", prompt: "Mysterious Japanese woman, dark wolf cut hair, sharp eyes, non-conformist beauty" },
    { name: "JP-11 陶器肌ドール", prompt: "Japanese woman with doll-like features, heavy bangs, flawless porcelain skin, surreal beauty" },
    { name: "JP-12 圧倒的美女オーラ", prompt: "Gorgeous Japanese woman, swept-back long hair, bold eyebrows, striking and charismatic" },
    { name: "JP-13 親しみボブ", prompt: "Friendly Japanese woman, out-curled short bob, expressive eyes, girl-next-door vibe" },
    { name: "JP-14 儚げ姫カット", prompt: "Fragile Japanese woman, hime cut hair, pale skin, small lips, melancholy beauty" },
    { name: "JP-15 包容力ミディアム", prompt: "Kind Japanese woman, ear-tucked medium hair, calm eyes, warm and soothing aura" },
    { name: "JP-16 文学少女おさげ", prompt: "Literary Japanese girl, loose braids, thin lips, quiet and solitary beauty" },
    { name: "JP-17 インナーカラー女子", prompt: "Modern Japanese girl, blonde inner-color hair, rebellious eyes, Harajuku street style" },
    { name: "JP-18 涼しげサイドポニー", prompt: "Refreshing Japanese woman, side ponytail, sharp profile, athletic and cool" },
    { name: "JP-19 意志の強いロング", prompt: "Strong-willed Japanese woman, heavy bangs, deep-set eyes, powerful presence" },
    { name: "JP-20 究極の初恋ボブ", prompt: "Ultimate Japanese beauty, natural bob, transparent skin, crystal clear eyes, nostalgic" },
    { name: "JP-21 あざとツインテール", prompt: "Calculatingly cute Japanese girl, wavy twin tails, large eyes, perfectly adorable" },
    { name: "JP-22 自然体セミロング", prompt: "Natural Japanese woman, effortless semi-long hair, minimalist beauty, authentic" },
    { name: "JP-23 アクティブ・アッシュ", prompt: "Active Japanese woman, ash short hair, small face, boyish sexiness" },
    { name: "JP-24 しっとり和風美人", prompt: "Elegant Japanese woman, loose half-up hair, traditional beauty, refined features" },
    { name: "JP-25 夜の都会・美女", prompt: "Confident Japanese woman, voluminous swept-up bangs, glamorous night-city aura" },
    { name: "JP-26 モテ系ゆるポニー", prompt: "Popular Japanese woman, fluffy ponytail, charming smile, universally attractive" },
    { name: "JP-27 ミニマル・ボブ", prompt: "Minimalist Japanese woman, center-parted bob, sharp and professional look" },
    { name: "JP-28 ガーリー編み込み", prompt: "Girly Japanese woman, braided hair, doll-like cute face, fairytale-like charm" },
    { name: "JP-29 エキゾチック・ウェーブ", prompt: "Exotic Japanese woman, long wavy hair, deep soulful eyes, passionate beauty" },
    { name: "JP-30 サブカル・パッツン", prompt: "Subculture Japanese girl, straight bangs bob, intense gaze, artistic personality" },
    { name: "JP-31 凛としたポニー", prompt: "Dignified Japanese woman, high ponytail, clean skin, athletic and noble aura" },
    { name: "JP-32 無防備シニヨン", prompt: "Relaxed Japanese woman, loose messy bun, sleepy eyes, natural and intimate" },
    { name: "JP-33 憧れの先輩", prompt: "Sexy Japanese woman, swept-back medium hair, intellectual and mature beauty" },
    { name: "JP-34 甘めワンカール", prompt: "Sweet Japanese woman, inward-curled hair tips, classy and feminine look" },
    { name: "JP-35 尖った金髪ショート", prompt: "Artistic Japanese woman, platinum blonde short hair, edgy and unique presence" },
    { name: "JP-36 妖艶ウェーブ", prompt: "Seductive Japanese woman, long dark wavy hair, mysterious and captivating shadow" },
    { name: "JP-37 純真おさげ", prompt: "Pure Japanese girl, simple braids, innocent and rustic beauty, countryside vibe" },
    { name: "JP-38 大人の余裕ロング", prompt: "Mature Japanese woman, side-parted long hair, calm and sophisticated aura" },
    { name: "JP-39 太陽の笑顔", prompt: "Energetic Japanese girl, high bun hair, bright smile, sun-kissed beauty" },
    { name: "JP-40 専属モデル風", prompt: "Fashionable Japanese woman, short bangs, modern features, high-fashion vibe" },
    { name: "JP-41 官能的ストレート", prompt: "Sensual Japanese woman, wet straight hair, intense gaze, provocative aura" },
    { name: "JP-42 ガラスの美少女", prompt: "Fragile Japanese girl, loose braids, pale skin, delicate and ethereal" },
    { name: "JP-43 女子アナ系王道", prompt: "Standard Japanese beauty, slanted bangs, universally loved and clean features" },
    { name: "JP-44 ジム系ヘルシー", prompt: "Fit Japanese woman, messy ponytail, healthy glow, athletic and attractive" },
    { name: "JP-45 自由なウェーブ", prompt: "Bohemian Japanese woman, center-parted waves, natural and stylish" },
    { name: "JP-46 神秘的パッツン", prompt: "Mystical Japanese woman, heavy straight bangs, cool and dark beauty" },
    { name: "JP-47 ふんわりマシュマロ", prompt: "Soft Japanese girl, fluffy bob hair, marshmallow-like soft skin" },
    { name: "JP-48 宝塚系ハンサム", prompt: "Handsome Japanese woman, swept-back short hair, dignified and noble beauty" },
    { name: "JP-49 ラフなハーフアップ", prompt: "Casual Japanese girl, half-up bun, daily natural cuteness" },
    { name: "JP-50 究極の正統派美人", prompt: "Perfect Japanese beauty, long silky black hair, golden ratio face, absolute masterpiece" }
  ],
  outfits: [], // 後でここに衣装を流し込むよ
  locations: [], // 後でここに場所を流し込むよ
  styles: [] // 後でここにスタイルを流し込むよ
};
